common:
  containerRegistry: todomicroservicesacr1234.azurecr.io
  ingress:
    className: azure-application-gateway
  env:
    name: CONNECTION_STRING
    value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:devtodomicrosqlsvr1234.database.windows.net,1433;Database=devtodomicrosqldb1234;Uid=sqladminuser;Pwd=P@ssw0rd1234!;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  
  strategy:
    type: RollingUpdate

todoui:
  replicaCount: 2
  image:
    name: todo-ui-app
    tag: latest
  port: 80
  servicePort: 80
  ingress:
    host: ui.puneetdevops.online

Addtask:
  replicaCount: 3
  image:
    name: add-todo-app
    tag: latest
  port: 80
  servicePort: 8000
  ingress:
    host: addtask.puneetdevops.online
        
Deletetask:
  replicaCount: 3
  image:
    name: delete-todo-app
    tag: latest
  port: 80
  servicePort: 8000
  ingress:
    host: deletetask.puneetdevops.online
Gettask:
  replicaCount: 3
  image:
    name: get-todo-app
    tag: latest
  port: 80
  servicePort: 8000
  ingress:
    host: gettask.puneetdevops.online