apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-ui-service
spec:
  selector:
    app: {{ .Release.Name }}-todo-ui
  ports:
  - port: {{ .Values.todoui.port }}
    targetPort: {{ .Values.todoui.servicePort }}
