apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-add-task-service
spec:
  selector:
    app: {{.Release.Name}}-todo-add-task
  ports:
  - port: {{ .Values.Addtask.port }}   
    targetPort: {{ .Values.Addtask.ServicePort }} 