apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-get-task-service
spec:
  selector:
    app: {{.Release.Name}}-todo-get-task
  ports:
  - port: {{ .Values.Gettask.port }}   
    targetPort: {{ .Values.Gettask.ServicePort }} 