apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-todo-delete-task-service
spec:
  selector:
    app: {{.Release.Name}}-todo-delete-task
  ports:
  - port: {{ .Values.Deletetask.port }}   
    targetPort: {{ .Values.Deletetask.ServicePort }}